In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
from scipy.stats import chi2_contingency

In [2]:
df = pd.read_csv('/media/prince/5A4E832F4E83034D/Fraud-Detector-ML/Data/Fraud_Data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588912 entries, 0 to 588911
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   transaction_id           588912 non-null  int64  
 1   is_fraud                 588912 non-null  int64  
 2   transaction_time         588912 non-null  int64  
 3   transaction_amount       588912 non-null  float64
 4   card_network             588912 non-null  object 
 5   card_type                588912 non-null  object 
 6   purchaser_email_domain   494686 non-null  object 
 7   device_type              140606 non-null  object 
 8   is_identity_seen_before  129173 non-null  object 
 9   user_os                  144028 non-null  object 
 10  user_browser             144028 non-null  object 
 11  environment              144028 non-null  object 
 12  environment_freq         144028 non-null  float64
 13  environment_risk         144028 non-null  float64
 14  devi

In [3]:
df['device_type'].unique()

array([nan, 'mobile', 'desktop'], dtype=object)

In [4]:
df['user_os'].unique()

array([nan, 'Android', 'iOS', 'Other', 'macOS', 'Windows', 'Linux'],
      dtype=object)

In [5]:
df['device_typ_os'] = df['device_type'] + '_' + df['user_os']

In [6]:
df['device_typ_os'].unique()

array([nan, 'mobile_Android', 'mobile_iOS', 'desktop_Other',
       'desktop_macOS', 'desktop_Windows', 'desktop_Linux',
       'mobile_Other', 'mobile_macOS', 'desktop_Android', 'mobile_Linux',
       'mobile_Windows', 'desktop_iOS'], dtype=object)

In [7]:
ct = pd.crosstab(df['device_typ_os'], df['is_fraud'])
(pd.crosstab(df['device_typ_os'], df['is_fraud'], normalize='index')) * 100

is_fraud,0,1
device_typ_os,,
desktop_Android,100.000000,0.000000
desktop_Linux,92.741935,7.258065
desktop_Other,88.398693,11.601307
desktop_Windows,96.546559,3.453441
desktop_iOS,100.000000,0.000000
desktop_macOS,97.811026,2.188974
mobile_Android,91.395460,8.604540
mobile_Linux,80.000000,20.000000
mobile_Other,86.878951,13.121049


In [8]:
chi2, p, dof, exp = chi2_contingency(ct)
print(p)
n = ct.values.sum()
cramers_v = np.sqrt(chi2 / (n * (min(ct.shape) - 1)))
print(cramers_v)

0.0
0.1555101057316735
